export const SELECT_SUPPLEMENT = 'SELECT_SUPPLEMENT';
export const SAVE_SUPPLEMENTS_REQUEST = 'SAVE_SUPPLEMENTS_REQUEST';
export const SAVE_SUPPLEMENTS_RESPONSE = 'SAVE_SUPPLEMENTS_RESPONSE';
export const SAVE_SUPPLEMENTS_ERROR = 'SAVE_SUPPLEMENTS_ERROR';
